# Generated by Django 3.1 on 2020-09-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('list_all_teams', 'Can list all teams'), ('list_team', 'Can list single team')]},
        ),
    ]
